### ISSUE TITLE
Error when running COJO - cojo.jma.cojo not found

### ISSUE THREAD

**Issue by AMCalejandro** [RajLabMSSM/echofinemap#5]
Hi,

I got the following error when trying to run COJO

```
+++ Multi-finemap:: COJO +++
[1] "+ COJO:: conditional analysis -- Conditioning on: rs4721411"
sh: 1: /home/acarrasco/.conda/envs/echoR/lib/R/library/echolocatoR/tools/gcta_1.92.1beta5_mac/bin/gcta64: Exec format error
[1] "+ COJO:: Processing results..."
Error in data.table::fread(file.path(cojo_dir, "cojo.jma.cojo")) : 
  File '/mnt/rreal/RDS/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/RESULTS_23.2.2022/mixedmodels_GWAS/axial_TryingCOJO/MAD1L1/COJO/cojo.jma.cojo' does not exist or is non-readable. getwd()=='/mnt/rreal/RDS/RDS/acarrasco/ANALYSES_WORKSPACE/EARLY_PD/POST_GWAS/ECHOLOCATOR/SCRIPTS'

```

I was looking at the code but I am not sure in which step "cojo.jma.cojo" file is generated. Does it come from running COJO?
In that case, it may be solved with RajLabMSSM/echofinemap#11

**Comment by bschilder** [comment]
@AMCalejandro I've rewritten much of the COJO code to make it easier to run and understand.
Try reinstalling `echofinemap` and check out the documentation `?echofinemap::COJO`.

It also automatically installs the GCTA-COJO executable (v1.93.2) via [`genetics.binaRies`](https://github.com/MRCIEU/genetics.binaRies), so you don't have to worry about version differences.
